# action.yaml
name: 'Flet Windows based on PyInstaller'
description: 'Customisable GitHub Action to package your flet python code  with PyInstaller for Windows'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  path:
    description: 'set entry-point script file.'
    required: True
    default: "main.py"
outputs:
  output:
    description: 'The output of PyInstaller'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
